version: '3.9'

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_awstools}"
    image: "localstack/${LOCALSTACK_IMAGE-localstack-light}"
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=cognito
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
    volumes:
      - ./.volumes/localstack/state:/var/lib/localstack/state
